version: "3"
services:
  flaskapp:
    build:
      context: ../backend
      target: builder
    stop_signal: SIGINT
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - my-network
  reactapp:
    build:
      context: ../frontend
    restart: always
    container_name: reactApp
    ports:
      - "3000:3000"
    stdin_open: true
    depends_on:
      - postgres
    networks:
      - my-network
  postgres:
    image: postgres:latest
    restart: always
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=0609
      - POSTGRES_DB=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/1-create_tables.sql
      - ./sql/fill_tables.sql:/docker-entrypoint-initdb.d/2-fill_tables.sql
      - ./sql/create_views.sql:/docker-entrypoint-initdb.d/3-create_views.sql
      - ./sql/create_stored_functions_and_triggers.sql:/docker-entrypoint-initdb.d/4create_stored_functions_and_triggers.sql
      - ./sql/create_indexes.sql:/docker-entrypoint-initdb.d/5-create_indexes.sql
    networks:
      - my-network
  pgadminer:
    image: dpage/pgadmin4
    restart: always
    container_name: pgadminer
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_CONFIG_SERVER_MODE=False
      - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False
      - PGADMIN_CONFIG_SKIP_SESSION_EXPIRATION=False
    ports:
      - "8080:80"
    networks:
      - my-network

networks:
  my-network:
