version: "3.8"

networks:
  mynetwork:
    name: mynetwork

services:
  reactapp:
    image: nklsdhbw/database-project:latest
    restart: always
    container_name: reactApp
    ports:
      - "3000:3000"
    stdin_open: true
    networks:
      - mynetwork

  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=0609
      - POSTGRES_DB=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./sql/fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql
    networks:
      - mynetwork

  flaskapp:
    image: nklsdhbw/flask-server:latest
    container_name: flaskApp
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    networks:
      - mynetwork
