version: "3.8"

networks:
  mynetwork:
    name: mynetwork

services:
  reactapp:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    restart: always
    container_name: reactApp
    ports:
      - "3000:3000"
    stdin_open: true
    networks:
      - mynetwork

  postgres:
    image: postgres:latest
    restart: always
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=0609
      - POSTGRES_DB=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/1-create_tables.sql
      - ./sql/fill_tables.sql:/docker-entrypoint-initdb.d/2-fill_tables.sql
      - ./sql/create_views.sql:/docker-entrypoint-initdb.d/3-create_views.sql
      - ./sql/create_stored_functions_and_triggers.sql:/docker-entrypoint-initdb.d/4create_stored_functions_and_triggers.sql
      - ./sql/create_indexes.sql:/docker-entrypoint-initdb.d/5-create_indexes.sql
    networks:
      - mynetwork

  flaskapp:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: flask-server
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    networks:
      - mynetwork
